"""BIDS-Derivatives output marking for ``iproc-app`` (T9).

A BIDS-App's ``output_dir`` should itself be a valid BIDS-Derivatives
dataset, which minimally means a top-level ``dataset_description.json``
declaring it a derivative (see the BIDS spec's "Derived dataset and
pipeline description" section). This module writes exactly that file; it
does not attempt full per-file BIDS-Derivatives naming for individual iProc
results (those keep their iProc-native names for now — see
``docs/usage.md``).
"""
from __future__ import annotations

import json
from importlib import metadata
from pathlib import Path

from iproc.__version__ import __version__ as IPROC_VERSION

BIDS_VERSION = "1.9.0"


def _dist_version() -> str:
    """The installed ``iproc`` distribution version.

    Falls back to the vendored ``iproc.__version__`` (e.g. ``v1.1.1``) only
    when the package metadata isn't available, such as running from a raw
    checkout that was never ``pip install``-ed. Mirrors
    ``iproc.app.cli._dist_version``.
    """
    try:
        return metadata.version("iproc")
    except metadata.PackageNotFoundError:
        return IPROC_VERSION


def write_dataset_description(output_dir: Path) -> Path:
    """Write ``output_dir/dataset_description.json`` marking it a derivative.

    Creates ``output_dir`` if it does not already exist. Idempotent:
    calling this more than once simply overwrites the file with the same
    content (modulo the installed version, if it changes between calls).

    Returns the path to the written file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    description = {
        "Name": "iProc (individualized fMRI preprocessing)",
        "BIDSVersion": BIDS_VERSION,
        "DatasetType": "derivative",
        "GeneratedBy": [
            {
                "Name": "iproc",
                "Version": _dist_version(),
                "CodeURL": "https://github.com/lobennett/iproc_py",
            }
        ],
        "HowToAcknowledge": (
            "This dataset was generated by iproc, a containerized, "
            "generalized repackaging of upstream iProc "
            "(https://github.com/harvard-nrg/iProc); please acknowledge "
            "upstream iProc when citing this pipeline."
        ),
    }

    out_path = output_dir / "dataset_description.json"
    out_path.write_text(json.dumps(description, indent=2) + "\n")
    return out_path
